# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run build --if-present
    - run: npx mocha test/sample.test.js

  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # ...
      - name: "Build & test"
        run: npm run build --if-present

      - uses: softprops/action-gh-release@v1
        with:
          repo_token: "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"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            *.exe
